config-version: 2
name: bratrax
version: 1.0.0
profile: bratrax
model-paths:
  - models/2
  - models/27
  - models/30
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  bratrax:
    +materialized: view
target-path: target
