bratrax:
  outputs:
    dev:
      dataset: cod
      job_execution_timeout_seconds: 50
      job_retries: 1
      keyfile: /Users/batibat/.config/gcloud/legacy_credentials/bratrax@bratrax-without-flattening.iam.gserviceaccount.com/adc.json
      location: US
      method: service-account
      priority: interactive
      project: bratrax-without-flattening
      threads: 1
      type: bigquery
  target: dev
