-- @block_type: explore
-- @model_type: table
-- Customer journey model from bratrax-without-flattening.production_tables.customer_journey
{{ config(
    materialized = 'view',
    alias = 'customer_journey_view'
) }}

SELECT
    client_id,
    write_key,
    event_id,
    analytics_session_id,
    anonymous_id,
    type,
    event_time,
    source,
    url,
    page_type,
    device,
    browser,
    country,
    city,
    email,
    customer_id,
    order_id,
    order_name,
    discount_amount,
    discount_code,
    order_revenue,
    quantity,
    tags,
    fulfillment_status,
    product_id,
    product_title,
    product_image,
    page_view_number,
    has_login_event,
    is_bounce,
    campaign_name,
    adset_name,
    ad_name,
    ad_id,
    ad_image_url,
    lead_click_ts,
    traffic_source,
    utm_medium,
    utm_campaign,
    utm_content,
    utm_term,
    event_date,
    event_hour,
    timezone,
    processed_at,
    customer_journey_processed_at
FROM {{ source('production_tables_no_flat', 'customer_journey') }}
