-- @block_type: explore
-- @model_type: table
-- Orders model from bratrax-without-flattening.production_tables.orders
{{ config(
    materialized = 'view',
    alias = 'orders_view'
) }}

SELECT
    order_id,
    customer_id,
    order_revenue,
    gross_revenue,
    net_revenue,
    created_at,
    event_date,
    client_id,
    write_key,
    platform,
    order_name,
    customer_email,
    customer_first_name,
    customer_last_name,
    customer_from_city,
    customer_from_country_code,
    customer_from_state_code,
    tags,
    note,
    discount_codes,
    fulfillment_status,
    source_name,
    source_category,
    cancelled_at,
    event_hour,
    timezone,
    discount_amount,
    taxes,
    shipping_price,
    refund_money,
    cost_of_goods,
    payment_gateway_costs,
    shipping_costs,
    handling_fees,
    amazon_estimated_fees,
    estimated_profit,
    product_quantity_sold_in_order,
    line_items_skus,
    line_items_titles,
    line_items_vendors,
    line_items_requires_shipping,
    line_items_gift_card,
    line_items_taxable,
    line_items_fulfillment_service,
    total_shipping_price,
    estimated_taxes,
    current_subtotal_price_shop,
    current_subtotal_price_presentment,
    orders_processed_at,
    DATE(TIMESTAMP_ADD(created_at, INTERVAL 10 HOUR)) as date_plus_10h
FROM {{ source('production_tables_no_flat', 'orders') }} 